# Ruby
# Package your Ruby application.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.7'

- script: |
    sudo gem update --system
    gem install bundler
    gem install bundler:2.1.4
    bundle install --retry=3 --jobs=4
  displayName: 'ovidiu bundle install'

- script: bundle exec jekyll build -d public
  displayName: 'ovidiu bundle exec jekyll build -d public'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'public'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true
  displayName: 'ovidiu Copy output files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'ovidiu Publish output files'
